dependencies {
    implementation project(':common')

    implementation 'org.bstats:bstats-bukkit:3.0.0'
    implementation 'com.tcoded:FoliaLib:0.3.3'
    implementation 'net.kyori:adventure-api:4.13.1'
    implementation 'net.kyori:adventure-text-minimessage:4.13.1'
    implementation 'net.kyori:adventure-platform-bukkit:4.3.4'

    compileOnly 'org.spigotmc:spigot-api:1.13.2-R0.1-SNAPSHOT'
}

processResources {
    filesMatching('plugin.yml') {
        expand 'pluginVersion': project.version
    }
    filesMatching('bungee.yml') {
        expand 'pluginVersion': project.version
    }
}