#    ___                __  __
#   /___\_ __   ___  /\ \ \/ /  ___   __ _(_)_ __
#  //  // '_ \ / _ \/  \/ / /  / _ \ / _` | | '_ \
# / \_//| |_) |  __/ /\  / /__| (_) | (_| | | | | |
# \___/ | .__/ \___\_\ \/\____/\___/ \__, |_|_| |_|
#       |_|                          |___/

# Official Website: https://www.nickuc.com
# Discord: https://www.nickuc.com/discord

# Polish translation made by Gh77ost#8539 <3
# Fixed by sus town#1347 :}

Messages:
  Title:
    # Message sent before login
    before-login:
      title: "<gradient:#7F5AF0:#2CB67D><bold>Witaj!</bold></gradient>"
      subtitle: "<#A0A0B0>Wpisz: /login [hasło]"
      delays:
        start: 0
        duration: 120
        end: 6
    # Message sent before registration
    before-register:
      title: "<gradient:#7F5AF0:#2CB67D><bold>Witaj!</bold></gradient>"
      subtitle: "<#A0A0B0>Wpisz: /register [hasło] [hasło]"
      delays:
        start: 0
        duration: 120
        end: 6
    # Message sent after login
    after-login:
      title: "<gradient:#7F5AF0:#2CB67D><bold>Weryfikacja!</bold></gradient>"
      subtitle: "Pomyślnie zalogowano!"
      delays:
        start: 0
        duration: 30
        end: 6
    # Message sent after registration
    after-register:
      title: "<gradient:#7F5AF0:#2CB67D><bold>Weryfikacja!</bold></gradient>"
      subtitle: "Pomyślnie zarejestrowano!"
      delays:
        start: 0
        duration: 30
        end: 6

  delay-kick:
    # Message sent when a user takes a long time to register
    register-kick: "<#E0575B>Minął czas rejestracji."

    # Message sent when a user takes a long time to log in
    login-kick: "<#E0575B>Minął czas logowania."

  successful-operations:
    # Message when a user exchanges their password
    password-changed: "<#5EC26A>Twoje hasło zostało zmienione pomyślnie."

    # Message sent when a user successfully logs
    successful-login: "<#5EC26A>Pomyślnie się zalogowałeś."

    # Message sent when a user successfully registers
    successful-register: "<#5EC26A>Pomyślnie się zarejestrowałeś."

    # Message sent when a player successfully disregisters
    unregister-kick: "<#E0575B>Rejestr został pomyślnie usunięty."

  kick-messages:
    # Message when a player tries to log on to the server with a small difference in the nickname
    nick-already-registered: "<#E0575B>Nie możesz wejść pod tym nickiem <nickname>\n<#E0575B>Ten użytkownik został zarejestrowany jako <realname>\n\n<#E0575B>By wejść na serwer musisz użyć starego nicku. Zwróć uwagę na wielkie litery!"

    # Message sent when a user misses many times
    failed-many-times: "<#E0575B>Zbyt wiele razy wpisałeś złe hasło."

    # Message sent when password entered is incorrect
    incorrect-password: "<#E0575B>Nie właściwe hasło! Spróbuj ponownie."

  error-messages:
    # Message sent when you are already logged in.
    already-login: "<#E0575B>Jesteś już zalogowany."

    # Message sent when a nickname has already been registered.
    already-registered: "<#E0575B>Ten pseudonim został już zarejestrowany."

    # Message sent when a nickname has not yet been registered.
    not-registered: "<#E0575B>Ten pseudonim nie został jeszcze zarejestrowany."

    # Message sent when the entered password is not equal to the second
    passwords-dont-match: "<#E0575B>Hasła nie są takie same."

    # Message sent when a player tries to change password by entering the same password as the current
    password-same-as-old: "<#E0575B>Wprowadzone hasło jest takie samo jak bieżące."

    # Message sent when the password entered is too large
    password-too-large: "<#E0575B>Podane hasło jest za długie."

    # Message sent when the password entered is too small
    password-too-small: "<#E0575B>Podane hasło jest za krótkie."

    # Message when a player does not possess the required permission
    insufficient-permissions: "<#E0575B>Nie masz uprawnień by to zrobić. <#A0A0B0>(<permission>)"

    # Message to kick a player now online
    already-online: "<#E0575B>Ten gracz jest aktualnie online."

    # Message to show that the command cannot be executed via console
    player-command-usage: "<#E0575B>To polecenie nie może zostać wykonane za pomocą konsoli."

    # Message shown when the plugin is reloaded
    plugin-reload-message: "<#F2C14E>Pomyślnie przeładowano plugin."

    # Komunikat wysyłany, gdy operacja na bazie danych nie została pomyślnie wykonana
    database-error: "<#E0575B>Przepraszamy, nie mogliśmy ukończyć tej operacji. Proszę spróbuj ponownie. [SQL FAIL]"

  other-messages:
    # Mensagem enviada para o uso do comando /logar
    message-login: "<#F2C14E>Użyj polecenia <#A0A0B0>/login [hasło]<#F2C14E>."

    # Mensagem enviada para o uso do comando /register
    message-register: "<#F2C14E>Użyj polecenia <#A0A0B0>/register [hasło] [hasło]<#F2C14E>."

    # Mensagem enviada para o uso do comando /mudarsenha
    message-changepassword: "<#F2C14E>Użyj polecenia <#A0A0B0>/changepassword [stare Hasło] [nowe Hasło]<#F2C14E>."

    # Wiadomość wysłana w celu użycia polecenia /unregister
    message-unregister: "<#F2C14E>Użyj polecenia <#A0A0B0>/unregister [bieżące hasło]<#F2C14E>."