#    ___                __  __
#   /___\_ __   ___  /\ \ \/ /  ___   __ _(_)_ __
#  //  // '_ \ / _ \/  \/ / /  / _ \ / _` | | '_ \
# / \_//| |_) |  __/ /\  / /__| (_) | (_| | | | | |
# \___/ | .__/ \___\_\ \/\____/\___/ \__, |_|_| |_|
#       |_|                          |___/

# Официальный сайт: https://www.nickuc.com
# Discord: https://www.nickuc.com/discord

# Russian translation made by Vadimus#3081 and github.com/Quantum-0 <3

Messages:
  Title:
    # Сообщение отправляется перед входом в систему
    before-login:
      title: "<gradient:#7F5AF0:#2CB67D><bold>Добро пожаловать!</bold></gradient>"
      subtitle: "<#A0A0B0>Использование: /login [пароль]"
      delays:
        start: 0
        duration: 9999
        end: 6
    # Сообщение отправляется перед регистрацией
    before-register:
      title: "<gradient:#7F5AF0:#2CB67D><bold>Добро пожаловать!</bold></gradient>"
      subtitle: "<#A0A0B0>Использование: /register [пароль] [повтор пароля]"
      delays:
        start: 0
        duration: 9999
        end: 6
    # Сообщение отправляется после успешного входа в систему
    after-login:
      title: ""
      subtitle: "<#5EC26A>Вы успешно вошли!"
      delays:
        start: 0
        duration: 60
        end: 6
    # Сообщение отправляется после успешной регистрации
    after-register:
      title: ""
      subtitle: "<#5EC26A>Вы успешно зарегистрировались!"
      delays:
        start: 0
        duration: 60
        end: 6

  delay-kick:
    # Сообщение отправляется, когда игрок слишком долго регистрируется
    register-kick: "<#E0575B>Время регистрации истекло."

    # Сообщение отправляется, когда игрок слишком долго входит в аккаунт
    login-kick: "<#E0575B>Вы слишком долго входили в аккаунт."

  successful-operations:
    # Сообщение отправляется, когда игрок меняет свой пароль
    password-changed: "<#5EC26A>Ваш пароль был успешно изменён."

    # Сообщение отправляется, когда игрок успешно входит в аккаунт
    successful-login: "<#5EC26A>Вы успешно вошли в аккаунт."

    # Сообщение отправляется, когда игрок успешно регистрируется
    successful-register: "<#5EC26A>Вы успешно зарегистрировались."

    # Сообщение отправляется, когда игрок удаляет свой аккаунт
    unregister-kick: "<#E0575B>Регистрация аккаунта успешно отозвана."

  kick-messages:
    # Сообщение отправляется, когда игрок пытается зайти на сервер с маленькой разницей в нике
    nick-already-registered: "<#E0575B>Вы не можете войти с ником <nickname>\n<#E0575B>Это имя пользователя уже зарегистрировано как <realname>\n\n<#E0575B>Для входа вы должны использовать свой никнейм без прописых/строчных букв"

    # Сообщение отправляется, когда игрок слишком много раз вводит неправильный пароль
    failed-many-times: "<#E0575B>Вы слишком много раз ввели неправильный пароль."

    # Сообщение отправляется, когда игрок вводит неправильный пароль
    incorrect-password: "<#E0575B>Неправильный пароль! Попытайтесь снова."

  error-messages:
    # Сообщение отправлено, когда вы уже вошли в систему.
    already-login: "<#E0575B>Вы уже авторизованы."

    # Сообщение отправляется, когда ник уже зарегистрирован.
    already-registered: "<#E0575B>Данное имя пользователя уже зарегистрировано."

    # Сообщение отправляется, когда ник еще не зарегистрирован.
    not-registered: "<#E0575B>Этот ник еще не зарегистрирован."

    # Сообщение отправляется, когда первый пароль не соответствует второму паролю
    passwords-dont-match: "<#E0575B>Пароли не совпадают."

    # Сообщение отправляется, когда игрок пытается сменить пароль, вводя тот же пароль, что и текущий
    password-same-as-old: "<#E0575B>Введённый пароль совпадает с текущим."

    # Сообщение отправляется, когда игрок вводит слишком длинный пароль
    password-too-large: "<#E0575B>Вы ввели слишком длинный пароль."

    # Сообщение отправляется, когда игрок вводит слишком короткий пароль
    password-too-small: "<#E0575B>Вы ввели слишком короткий пароль."

    # Сообщение отправляется, когда у игрока недостаточно прав для использования какой-либо команды
    insufficient-permissions: "<#E0575B>У вас нет прав для использования этой команды. <#A0A0B0>(<permission>)"

    # Сообщение выводится, когда игрока кикает из-за того, что он уже зашёл на сервер
    already-online: "<#E0575B>Этот игрок уже зашёл на сервер."

    # Сообщение отправляется, если эту команду нельзя выполнить в консоли
    player-command-usage: "<#E0575B>Эту команду нельзя использовать в консоли."

    # Сообщение отправляется после перезагрузки плагина
    plugin-reload-message: "<#F2C14E>OpenLogin успешно перезагружен."

    # Сообщение отправляется, если операция с базой данных не была успешно выполнена
    database-error: "<#E0575B>К сожалению, нам не удалось выполнить эту операцию. Пожалуйста, попробуйте еще раз. [SQL FAIL]"

  other-messages:
    # Сообщение для использования команды /login
    message-login: "<#F2C14E>Введите: <#A0A0B0>/login [пароль]<#F2C14E>."

    # Сообщения для использования команды /register
    message-register: "<#F2C14E>Введите: <#A0A0B0>/register [пароль] [повтор пароля]<#F2C14E>."

    # Сообщение для команды смены пароля /changepassword
    message-changepassword: "<#F2C14E>Введите: <#A0A0B0>/changepassword [текущий пароль] [новый пароль]<#F2C14E>."

    # Сообщение отправлено для использования команды /unregister
    message-unregister: "<#F2C14E>Используйте команду <#A0A0B0>/unregister [текущий пароль]<#F2C14E>."
