#    ___                __  __
#   /___\_ __   ___  /\ \ \/ /  ___   __ _(_)_ __
#  //  // '_ \ / _ \/  \/ / /  / _ \ / _` | | '_ \
# / \_//| |_) |  __/ /\  / /__| (_) | (_| | | | | |
# \___/ | .__/ \___\_\ \/\____/\___/ \__, |_|_| |_|
#       |_|                          |___/

# Official Website: https://www.nickuc.com
# Discord: https://www.nickuc.com/discord

# Tradotto in Italiano da Peppe73
# Spigot: https://www.spigotmc.org/members/peppe73.693388/

Messages:
  Title:
    # Messaggio inviato prima del login
    before-login:
      title: "<gradient:#7F5AF0:#2CB67D><bold>Benvenuto!</bold></gradient>"
      subtitle: "<#A0A0B0>Per il login usa: /login [tua password]"
      delays:
        start: 0
        duration: 9999
        end: 6
    # Messaggio inviato prima della registrazione
    before-register:
      title: "<gradient:#7F5AF0:#2CB67D><bold>Benvenuto!</bold></gradient>"
      subtitle: "<#A0A0B0>Per registrarti usa: /register [tua password] [tua password]"
      delays:
        start: 0
        duration: 9999
        end: 6
    # Messaggio inviato dopo il login
    after-login:
      title: ""
      subtitle: "<#5EC26A>Hai effettuato il log in con successo!"
      delays:
        start: 0
        duration: 60
        end: 6
    # Messaggio inviato dopo la registrazione
    after-register:
      title: ""
      subtitle: "<#5EC26A>Ti sei registrato con successo!"
      delays:
        start: 0
        duration: 60
        end: 6

  delay-kick:
    # Messaggio inviato quando un utente impiega molto tempo per registrarsi
    register-kick: "<#E0575B>Hai impiegato troppo tempo per registrarti."

    # Messaggio inviato quando un utente impiega molto tempo per accedere
    login-kick: "<#E0575B>Hai impiegato troppo tempo per accedere."

  successful-operations:
    # Messaggio quando un utente scambia la propria password
    password-changed: "<#5EC26A>La tua password è stata cambiata con successo."

    # Messaggio inviato quando un utente accede con successo
    successful-login: "<#5EC26A>Hai effettuato l'accesso con successo."

    # Messaggio inviato quando un utente si registra correttamente
    successful-register: "<#5EC26A>Ti sei registrato con successo."

    # Messaggio inviato quando un giocatore si annulla con successo
    unregister-kick: "<#E0575B>Hai annullato la registrazione con successo."

  kick-messages:
    # Messaggio quando un giocatore tenta di accedere al server con una piccola differenza nel nickname
    nick-already-registered: "<#E0575B>Non puoi entrare con questo nickname <nickname>\n<#E0575B>Questo nome utente è già registrato come <realname>\n\n<#E0575B>Per entrare, devi usare il tuo nickname senza maiuscole/minuscole"

    # Messaggio inviato quando un utente perde molte volte
    failed-many-times: "<#E0575B>Password errata."

    # Messaggio inviato quando la password inserita non è corretta
    incorrect-password: "<#E0575B>Password errata. Per favore riprova."

    # Messaggio inviato quando un giocatore inserisce un nickname non valido.
    invalid-nickname: "<#E0575B>Spiacente, stai usando un nickname non valido."

  error-messages:
    # Messaggio inviato quando sei già loggato.
    already-login: "<#E0575B>Sei già loggato."

    # Messaggio inviato quando è già stato registrato un nickname.
    already-registered: "<#E0575B>Questo nickname è già stato registrato."

    # Messaggio inviato quando un nickname non è stato ancora registrato.
    not-registered: "<#E0575B>Questo nickname è ancora libero."

    # Messaggio inviato quando la password inserita non è uguale alla seconda
    passwords-dont-match: "<#E0575B>Le password non sono le stesse."

    # Messaggio inviato quando un giocatore tenta di cambiare la password inserendo la stessa password di quella corrente
    password-same-as-old: "<#E0575B>La password inserita è la stessa di quella corrente."

    # Messaggio inviato quando la password inserita è troppo grande
    password-too-large: "<#E0575B>La password inserita è troppo lunga."

    # Messaggio inviato quando la password inserita è troppo piccola
    password-too-small: "<#E0575B>La password inserita è troppo corta."

    # Messaggio quando un giocatore non possiede l'autorizzazione richiesta
    insufficient-permissions: "<#E0575B>Non sei autorizzato ad eseguire questo comando. <#A0A0B0>(<permission>)"

    # Messaggio per cacciare un giocatore ora online
    already-online: "<#E0575B>Questo giocatore è già online."

    # Messaggio per mostrare che il comando non può essere eseguito tramite console
    player-command-usage: "<#E0575B>Questo comando è stato disattivato tramite console."

    # Messaggio mostrato quando il plugin viene ricaricato.
    plugin-reload-message: "<#F2C14E>Plugin ricaricato con successo."

    # Messaggio inviato quando un'operazione sul database non è stata eseguita correttamente
    database-error: "<#E0575B>Spiacenti, non è stato possibile completare questa operazione. Per favore riprova. [SQL FAIL]"

  other-messages:
    # Messaggio inviato per o utilizzando il comando /login
    message-login: "<#F2C14E>Usa il comando /login [password]"

    # Messaggio inviato per o utilizzando il comando /register
    message-register: "<#F2C14E>Usa il comando /register [password] [password]"

    # Messaggio inviato per o utilizzando il comando /mudarsenha
    message-changepassword: "<#F2C14E>Usa il comando /changepassword [current password] [new password]"

    # Messaggio inviato per utilizzare il /unregister command
    message-unregister: "<#F2C14E>Usa il comando /unregister [current password]"