#    ___                __  __
#   /___\_ __   ___  /\ \ \/ /  ___   __ _(_)_ __
#  //  // '_ \ / _ \/  \/ / /  / _ \ / _` | | '_ \
# / \_//| |_) |  __/ /\  / /__| (_) | (_| | | | | |
# \___/ | .__/ \___\_\ \/\____/\___/ \__, |_|_| |_|
#       |_|                          |___/

# Офіційний сайт розробника: https://www.nickuc.com
# Discord: https://www.nickuc.com/discord

# Translation made by @who22

Messages:
  Title:
    # Повідомлення відправляється перед входом до системи
    before-login:
      title: "<gradient:#7F5AF0:#2CB67D><bold>Вітаємо!</bold></gradient>"
      subtitle: "<#A0A0B0>Увійдіть: /login [пароль]"
      delays:
        start: 0
        duration: 9999
        end: 6
    # Повідомлення відправляєтьяся перед реаєстрацією
    before-register:
      title: "<gradient:#7F5AF0:#2CB67D><bold>Вітаємо!</bold></gradient>"
      subtitle: "<#A0A0B0>Зареєструйтеся: /register [пароль] [повтор паролю]"
      delays:
        start: 0
        duration: 9999
        end: 6
    # Повідомлення відправляється після успішного входу
    after-login:
      title: ""
      subtitle: "<#5EC26A>Ви успішно увійшли!"
      delays:
        start: 0
        duration: 60
        end: 6
    # Повідомлення відправляється після успішної реєстрації
    after-register:
      title: ""
      subtitle: "<#5EC26A>Ви успішно зареєструвались!"
      delays:
        start: 0
        duration: 60
        end: 6

  delay-kick:
    # Повідомлення відправляється, якщо гравець занадто довго реєструється
    register-kick: "<#E0575B>Час реєстрації вичерпано."

    # Повідомлення відправляється, якщо гравець занадто довго входить в акаунт
    login-kick: "<#E0575B>Ви занадто довго входили в акаунт."

  successful-operations:
    # Повідомлення відправляється, якщо гравець змінює пароль
    password-changed: "<#5EC26A>Ваш пароль успішно змінений."

    # Повідомлення відправляється, якщо гравець входить в акаунт
    successful-login: "<#5EC26A>Ви успішно увійли в акаунт."

    # Повідомлення відправляється, якщо гравець успішно реєструється
    successful-register: "<#5EC26A>Ви успішно зареєструвались."

    # Повідомлення відправляється, якщо гравець видаляє акаунт
    unregister-kick: "<#E0575B>Реєстрація акаунту успішно відкликана."

  kick-messages:
    # Повідомлення відправляється, якщо гравець намагається зайти з невеликою різницею в нікнеймі
    nick-already-registered: "<#E0575B>Ви не можете увійти з ніком <nickname>\n<#E0575B>Це ім'я користувача все зареєстровано як <realname>\n\n<#E0575B>Для входу ви повинні вказати нікнейм без прописних/друкованих літер."

    # Повідомлення відправляється, якщо гравець багато разів вводить хибний пароль
    failed-many-times: "<#E0575B>Вы занадто багато разів ввели хибний пароль."

    # Повідомлення відправляється, якщо гравець вводить хибний пароль
    incorrect-password: "<#E0575B>Пароль хибний! Спробуйте ще раз."

  error-messages:
    # Повідомлення відправляється, коли ви вже увійшли в систему
    already-login: "<#E0575B>Ви вже авторизовані."

    # Повідомлення відправляється, якщо нік вже зареєстрований
    already-registered: "<#E0575B>Дане ім'я користувача вже зареєстроване."

    # Повідомлення відправляється, якщо нік ще не зареєстрований
    not-registered: "<#E0575B>Це ім'я користувача ще не зареєстроване."

    # Повідомлення відправляється, коли перший пароль не співпадає з другим
    passwords-dont-match: "<#E0575B>Паролі не співпадають."

    # Повідомлення відправляється, коли гравець намагається змінити свій пароль на свій теперішній
    password-same-as-old: "<#E0575B>Введений пароль співпадає з вашим теперішнім."

    # Повідомлення відправляється, якщо гравець вводить занадто довгий пароль
    password-too-large: "<#E0575B>Ви ввели занадто довгий пароль."

    # Повідомлення відправляється, якщо гравець вводить занадто короткий пароль
    password-too-small: "<#E0575B>Ви ввели занадто короткий пароль."

    # Повідомлення відправляється, якщо у гравця недостатньо прав на виконання команди
    insufficient-permissions: "<#E0575B>У вас немає прав на використання цієї команди. <#A0A0B0>(<permission>)"

    # Повідомлення відправляється, коли гравця кікає з серверу через наявну активну сесію
    already-online: "<#E0575B>Цей гравець вже увійшов на сервер."

    # Повідомлення відправляється, якщо команду не можна виконати в консолі
    player-command-usage: "<#E0575B>Цю команду неможна використовувати в консолі."

    # Повідомлення відправляється після перезавантаження плагіну
    plugin-reload-message: "<#F2C14E>OpenLogin успішно перезевантажено."

    # Повідомлення відправляється, якщо операція з базою даних провалилася
    database-error: "<#E0575B>На жаль, нам не вдалося виконати цю операцію. Будь-ласка, спробуйте ще раз. [SQL FAIL]"

  other-messages:
    # Підказка з використання команди /login
    message-login: "<#F2C14E>Введіть: <#A0A0B0>/login [пароль]<#F2C14E>."

    # Підказка з використання команди /register
    message-register: "<#F2C14E>Введіть: <#A0A0B0>/register [пароль] [повтор паролю]<#F2C14E>."

    # Підказка з використання команди /changepassword
    message-changepassword: "<#F2C14E>Введіть: <#A0A0B0>/changepassword [теперішній пароль] [новий пароль]<#F2C14E>."

    # Підказка з використання команди /unregister
    message-unregister: "<#F2C14E>Використовуйте команду <#A0A0B0>/unregister [теперішній пароль]<#F2C14E>."
