#          __             _
#  _ __   / /  ___   __ _(_)_ __
# | '_ \ / /  / _ \ / _` | | '_ \
# | | | / /__| (_) | (_| | | | | |
# |_| |_\____/\___/ \__, |_|_| |_|
#                   |___/

# Official Website: https://www.nickuc.com
# Discord: https://www.nickuc.com/discord

# WARNING: This is a translation made to nLogin. It will probably be compatible with all features of OpeNLogin.

# Lithuanian translation made by SkirmisLTU (Discord: SkirmisLTU#3310)

Messages:
  Title:
    # Message sent before login.
    before-login:
      title: "<gradient:#7F5AF0:#2CB67D><bold>Sveiki!</bold></gradient>"
      subtitle: "<#A0A0B0>Naudokite: /login [Tavo slaptažodis]"
      delays:
        start: 0
        duration: 9999
        end: 6
    # Message sent before registration.
    before-register:
      title: "<gradient:#7F5AF0:#2CB67D><bold>Sveiki!</bold></gradient>"
      subtitle: "<#A0A0B0>Naudokite: /register [Slaptažodis] [Slaptažodis]"
      delays:
        start: 0
        duration: 9999
        end: 6
    # Message sent after login.
    after-login:
      title: ""
      subtitle: "<#5EC26A>Jūs sėkmingai prisijungėte!"
      delays:
        start: 0
        duration: 60
        end: 6
    # Message sent after registration.
    after-register:
      title: ""
      subtitle: "<#5EC26A>Jūs sėkmingai Užsiregistravote!"
      delays:
        start: 0
        duration: 60
        end: 6
    # Message sent when you miss a password.
    incorrect-password:
      title: ""
      subtitle: "<#E0575B>Neteisingas slaptažodis!"
      delays:
        start: 0
        duration: 60
        end: 6
    # Message sent when already logged in.
    already-login:
      title: ""
      subtitle: "<#E0575B>Jūs jau prisijungęs!"
      delays:
        start: 0
        duration: 60
        end: 6
    # Message sent when already registered.
    already-registered:
      title: ""
      subtitle: "<#E0575B>Jūs jau prisiregistavęs!"
      delays:
        start: 0
        duration: 60
        end: 6
    # Message sent when passwords are not equal.
    passwords-dont-match:
      title: ""
      subtitle: "<#E0575B>Slaptažodžiai nesutampa!"
      delays:
        start: 0
        duration: 60
        end: 6
    # Message sent when session is continued.
    session-login:
      title: ""
      subtitle: "<#F2C14E>Jūsų prisijungimo sesija yra tęsiama."
      delays:
        start: 0
        duration: 60
        end: 6
    # Message sent when you are an original player.
    premium-login:
      title: ""
      subtitle: "<#F2C14E>Jūsų paskyra yra unikali, sėkmingai prisijungėte."
      delays:
        start: 0
        duration: 60
        end: 6
    # Message sent when a login session is continued.
    plugin-reload:
      title: ""
      subtitle: "<#5EC26A>Konfigūracijos ir kalbos failai buvo perkrauti."
      delays:
        start: 0
        duration: 60
        end: 6
    # Message sent from backup system.
    backup:
      title: ""
      subtitle: "<#5EC26A>Atsarginė kopija sukurta sėkmingai."
      delays:
        start: 0
        duration: 90
        end: 6
    # Message sent from backup system.
    backup-error:
      title: ""
      subtitle: "<#E0575B>Neišėjo sukurti atsarginės kopijos."
      delays:
        start: 0
        duration: 90
        end: 6
    # Message sent from security system.
    security-warning:
      title: ""
      subtitle: "<#E0575B>Chat'e išsiustas naujas saugumo įspėjimas"
      delays:
        start: 0
        duration: 60
        end: 6

  action-bar:
    # Message sent on the player's actionbar before login (singular).
    singular: "<#E0575B>Jūs turite {0} sekundę, kad {prisijunktumėte/Užsiregistruotumėte}."

    # Message sent on the player's actionbar before login (plural).
    plural: "<#E0575B>Jūs turite {0} sekundes kad {lprisijunktumėte/Užsoregistruotumėte}."

  delay-kick:
    # Message sent when a user takes a long time to register.
    register-kick: "<#E0575B>Per ilgai užtrukote registruodamiesi."

    # Message sent when a user takes a long time to log in.
    login-kick: "<#E0575B>Per ilgai užtrukote prisijunkdami."

  successful-operations:
    # Message when a user exchanges their password.
    password-changed: "<#5EC26A>Jūsų slaptažodis buvo sėkmingai pakeistas."

    # Message sent when a user successfully logs.
    successful-login: "<#5EC26A>Jūs sėkmingai prisijungėte."

    # Message sent when a user logs in with an original account.
    successful-premium-login: "<#5EC26A>Jūs esate automatiškai prisijungęs, kai naudojate unikalią paskyrą."

    # Message sent when a user logs in using the same ip address.
    successful-session-login: "<#5EC26A>Jūsų prisijungimo sesija yra tęsiama."

    # Message sent when a user successfully registers.
    successful-register: "<#5EC26A>Jūs sėkmingai užsiregistravote."

    # Message sent when you force a player's login.
    forcelogin: "<#F2C14E>Jūs buvote prijunktas {0}"

    # Message sent when a player successfully unregister.
    unregister-kick: "<#E0575B>Jūs sėkmingai išsiregistravote."

    # Message sent when a configuration is finished
    config-finished: "<#5EC26A>Configuracija baigta."

    # Message sent when a configuration is cancelled
    config-cancelled: "<#E0575B>Veiksmas atšauktas."

  kick-messages:
    # Message when a player tries to log on to the server with a small difference in the nickname.
    nick-already-registered: "<#E0575B>Jūs negalite įeiti su slapyvardziu <nickname>\n<#E0575B>dėl to nes šis slapyvardis jau užregistruotas kaip <realname>\n\n<#E0575B>Kad, įeiti turite naudoti savo slapyvardį be didžiųjų/mažųjų raidžių"

    # Message sent when a user misses many times.
    failed-many-times: "<#E0575B>Įvedėte neteisingą slaptažodį."

    # Message sent when password entered is incorrect.
    incorrect-password: "<#E0575B>Neteisingas slaptažodis. Bandykite dar kartą."

    # Message sent when the security questions answer is incorrect.
    incorrect-answer: "<#E0575B>Neteisingas atsakymas. Bandykite dar kartą."

    # Message sent when server is still starting.
    wait-server-start: "<#E0575B>Serveris dar nėra visiškai paleistas.\n<#E0575B>Truputi palaukite, kad prisijunkti."

    # Message sent when an IP is blocked by suspected invasion.
    account-blocked: "<#E0575B>Jūsų adresas buvo užblokuotas dėl įtariamos invazijos.\n<#E0575B>Likęs užblokavimo laikas: {0}"

    # Message sent when two-factor system temporary password is incorrect.
    incorrect-temporary-password: "<#E0575B>Neteisingas slaptažodis.Bandykite dar kartą."

    # Message to kick a user with an invalid nickname.
    invalid-nickname: "<#E0575B>Jūsų slapyvardis yra neteisingas, iš vardo pašalinkite tarpus, simbolius ir netinkamus simbolius."

    # Message sent when the player's account has already been registered as unique.
    premium-account: "<#E0575B>Atsiprašome, bet premium vartotojas (nusipirkęs minecraft) jau prisijungė prie šios paskyros.\n<#E0575B>Norėdami žaisti serveryje, turite naudoti kitą slapyvardį.\n\nJei esate šios paskyros savininkas, pabandykite iš naujo paleisti „Minecraft“."

  security-messages:
    # Message sent when a user was protected by the heuristic system.
    hacking-attack-warning:
      - ""
      - " <#E0575B><bold>SAUGUMO ĮSPĖJIMAS"
      - " <#E0575B>Saugumo sistema užblokavo galimas įsilaužimo atakas jūsų paskyroje."
      - " <#E0575B>Buvo bandyta tris kartus nesėkmingai prisijungti."
      - ""
      - " <#F2C14E><bold>PATARIMAS: <#F2C14E>NAudokite skirtingus slaptažodžius skirtinguose serveriuose."

    # Message sent when a user was protected more than once by the heuristic system.
    hacking-attack-warning2:
      - ""
      - " <#E0575B><bold>SAUGUMO ĮSPĖJIMAS"
      - " <#E0575B>Saugumo sistema užblokavo {0} galimas įsilaužimo atakas jūsų paskyroje."
      - " <#E0575B>Buvo bandyta tris kartus nesėkmingai prisijungti."
      - ""
      - " <#F2C14E>&Susisiekite su serverio administatoriais."
      - ""

    # Message sent when a user uses a weak password.
    weak-password:
      - ""
      - " <#E0575B>Užregistruotas slaptažodis laikomas nesaugiu."
      - " <#E0575B>Norėdami pagerinti saugumą, naudokite raides, skaičius ir simbolius."
      - " <#E0575B>Saugaus slaptažodžio pavyzdys: {0}"
      - ""

    # Message sent when a player has not yet registered the security questions.
    security-question-warn-message:
      - ""
      - " <#E0575B><bold>APSAUGOS KLAUSIMAI"
      - " <#A0A0B0>Norėdami užsiregistruoti, spustelėkite šį pranešimą"
      - " <#E0575B>Apsaugos klausimai<#A0A0B0>. Tai darydami"
      - " <#A0A0B0>sumažinsite įsilaužimo tikimybę."
      - ""

    # Message sent when a security question is being added.
    security-question-add:
      - ""
      - " <#F2C14E>{0}"
      - ""
      - " <#A0A0B0>Norėdami atšaukti operaciją, įveskite [white]'cancel'."
      - " <#A0A0B0>Spustelėkite šį pranešimą, kad sugeneruotumėte kitą klausimą."
      - ""

    # Message sent when a security question should be reviewed.
    security-question-check:
      - ""
      - " <#5EC26A>Prieš patvirtindami, patikrinkite informaciją:"
      - ""
      - " <#A0A0B0>{0}: [white]'{1}'"
      - ""
      - " <#5EC26A>Jei esate tikras, įveskite [white]'confirm'<#5EC26A>."
      - " <#F2C14E>Jei įvedėte kažką ne taip, įveskite [white]'repeat'<#F2C14E>."
      - " <#E0575B>Jei norite atšaukti šią operaciją, įveskite [white]'cancel'<#E0575B>."
      - ""

    # Message sent when security questions are requested.
    security-question-request:
      - ""
      - " <#5EC26A>Atsiprašome, bet reikalingas tapatybės patvirtinimas."
      - " <#5EC26A>Atsakykite į pateiktą klausimą chat'e:"
      - ""
      - " <#56CCF2>{0}"
      - ""

    # Message sent when security questions are requested a second time.
    security-question-request2:
      - "<#5EC26A>Kitas klausimas..."
      - ""
      - " <#56CCF2>{0}"
      - ""

  error-messages:
    # Message sent when you are already logged in.
    already-login: "<#E0575B>Jūs jau esate prisijungęs."

    # Message sent when a user is already logged in.
    already-login2: "<#E0575B>Šis žaidėjau jau prisijungęs."

    # Message sent when a nickname has already been registered.
    already-registered: "<#E0575B>Šis slapyvardis jau buvo užregistruotas."

    # Message sent when a nickname has not yet been registered.
    not-registered: "<#E0575B>Šis slapyvardis dar nebuvo užregistruotas."

    # Message sent when the entered password is not equal to the second.
    passwords-dont-match: "<#E0575B>Slaptažodžiai nėra vienodi."

    # Message sent when a player does not confirm your password.
    need-password-confirmation: "<#E0575B>Turite patvirtinti savo slaptažodį."

    # Message sent when a user does not have a temporary password.
    no-temporary-password: "<#E0575B>Laikinas slaptažodis dar nesugeneruotas."

    # Message sent when IP limits per player pass the limit.
    address-limiter-warning: "<#E0575B>Jūs išnaudojote žaidėjų limitą per IP adresą."

    # Message sent when a player tries to change password by entering the same password as the current.
    password-same-as-old: "<#E0575B>Įvestas slaptažodis yra toks pats kaip dabartinis."

    # Message sent when the password entered is too large.
    password-too-large: "<#E0575B>Įvestas slaptažodis per ilgas."

    # Message sent when the password entered is too small.
    password-too-small: "<#E0575B>Įvestas slaptažodis per trumpas."

    # Message sent when a user attempts to disable nLogin using PlugMan/System.
    plugman-block: "<#E0575B>Jūs negalite liesti plugino (naudokite /nlogin reload)."

    # Message when a player does not possess the required permission.
    insufficient-permissions: "<#E0575B>Jūs neturite leidimo vykdyti šią komandą. <#A0A0B0>(<permission>)"

    # Message to show the use of a command.
    command-usage: "<#E0575B>Jūs turite naudoti {0}."

    # Message to kick a player now online.
    already-online: "<#E0575B>Šis žaidėjas jau prisijungęs."

    # Message to display that a player is not online.
    offline-error: "<#E0575B>Norimas žaidėjas neprisijungęs."

    # Message to show that the command cannot be executed via console.
    player-command-usage: "<#E0575B>Ši komanda buvo išjungta per konsolę."

    # Message to show that a command can only be executed by the console.
    console-command-usage: "<#E0575B>Šią komandą galima naudoti tik per konsolę."

    # Message shown when the plugin is reloaded.
    plugin-reload-message: "<#F2C14E>Papildinys sėkmingai perkrautas."

    # Message shown when the function of a command is disabled.
    command-function-disabled: "<#E0575B>Komandos funkcija {0} yra išjungta."

    # Message sent when a database operation has not been successfully performed.
    database-error: "<#E0575B>Deja, mums nepavyko užbaigti šios operacijos. Prašau, pabandykite dar kartą. [SQL FAIL]"

  other-messages:
    # Hover message: /login.
    hover-message-login: "<#A0A0B0>Spustelėkite čia, kad užbaigtumėte komandą ir greitai prisijungtumėte."

    # Hover message: /register.
    hover-message-register: "<#A0A0B0>Spustelėkite čia, kad užbaigtumėte komandą ir greitai užregistruotumėte."

    # Command usage: /login
    message-login: "<#F2C14E>Naudokite komandą <#A0A0B0>/login [slaptažodis]<#F2C14E>."

    # Command usage: /register
    message-register: "<#F2C14E>Naudokite komandą <#A0A0B0>/register [slaptažodis] [slaptažodis]<#F2C14E>."

    # Command usage: /changepassword
    message-changepassword: "<#F2C14E>Naudokite komandą <#A0A0B0>/changepassword [dabartinis slaptažodis] [naujas slaptažodis]<#F2C14E>."

    # Command usage: /checkprofile
    message-verify: "<#F2C14E>Naudokite komandą <#A0A0B0>/checkprofile [žaidėjas]<#F2C14E>."

    # Command usage: /unregister
    message-unregister: "<#F2C14E>Naudokite komandą <#A0A0B0>/unregister [dabartinis slaptažodis]<#F2C14E>."