#    ___                __  __
#   /___\_ __   ___  /\ \ \/ /  ___   __ _(_)_ __
#  //  // '_ \ / _ \/  \/ / /  / _ \ / _` | | '_ \
# / \_//| |_) |  __/ /\  / /__| (_) | (_| | | | | |
# \___/ | .__/ \___\_\ \/\____/\___/ \__, |_|_| |_|
#       |_|                          |___/

# Official Website: https://www.nickuc.com
# Discord: https://www.nickuc.com/discord

# Argentinean translation made by Gann4

Messages:
  Title:
    # Message sent before login
    before-login:
      title: "<gradient:#7F5AF0:#2CB67D><bold>¡Bienvenido!</bold></gradient>"
      subtitle: "<#A0A0B0>Usá: /login [contraseña]"
      delays:
        start: 0
        duration: 9999
        end: 6
    # Message sent before registration
    before-register:
      title: "<gradient:#7F5AF0:#2CB67D><bold>¡Bienvenido!</bold></gradient>"
      subtitle: "<#A0A0B0>Usá: /register [contraseña] [contraseña]"
      delays:
        start: 0
        duration: 9999
        end: 6
    # Message sent after login
    after-login:
      title: ""
      subtitle: "<#5EC26A>¡Iniciaste sesión correctamente!"
      delays:
        start: 0
        duration: 60
        end: 6
    # Message sent after register
    after-register:
      title: ""
      subtitle: "<#5EC26A>¡Te registraste correctamente!"
      delays:
        start: 0
        duration: 60
        end: 6

  delay-kick:
    # Message sent when a user takes a long time to register
    register-kick: "<#E0575B>Tardaste mucho en registrarte."

    # Message sent when a user takes a long time to log in
    login-kick: "<#E0575B>Tardaste mucho en iniciar sesión."

  successful-operations:
    # Message when a user exchanges their password
    password-changed: "<#5EC26A>Tu contraseña se cambió correctamente."

    # Message sent when a user successfully logs
    successful-login: "<#5EC26A>Iniciaste sesión correctamente."

    # Message sent when a user successfully registers
    successful-register: "<#5EC26A>Te registraste correctamente."

    # Message sent when a player successfully disregisters
    unregister-kick: "<#E0575B>Cancelaste tu registro correctamente."

  kick-messages:
    # Message when a player tries to log on to the server with a small difference in the nickname
    nick-already-registered: "<#E0575B>No podés registrarte como <nickname>\n<#E0575B>Este nombre de usuario ya se registró como <realname>\n\n<#E0575B>Para entrar, tenés que usar tu nickname sin mayúsculas o minúsculas."

    # Message sent when a user misses many times
    failed-many-times: "<#E0575B>Introduciste una contraseña incorrecta."

    # Message sent when password entered is incorrect
    incorrect-password: "<#E0575B>Contraseña incorrecta. Por favor, intenta de nuevo."

  error-messages:
    # Message sent when you are already logged in.
    already-login: "<#E0575B>Ya iniciaste sesión."

    # Message sent when a nickname has already been registered.
    already-registered: "<#E0575B>Este usuario ya está registrado."

    # Message sent when a nickname has not yet been registered.
    not-registered: "<#E0575B>Este usuario todavía no está registrado."

    # Message sent when the entered password is not equal to the second
    passwords-dont-match: "<#E0575B>Las contraseñas no coinciden."

    # Message sent when a player tries to change password by entering the same password as the current
    password-same-as-old: "<#E0575B>La nueva contraseña es igual a la que ya tenés. Cambiala."

    # Message sent when the password entered is too large
    password-too-large: "<#E0575B>La contraseña es muy larga."

    # Message sent when the password entered is too small
    password-too-small: "<#E0575B>La contraseña es muy corta."

    # Message when a player does not possess the required permission
    insufficient-permissions: "<#E0575B>No tenés permisos para ejecutar este comando. <#A0A0B0>(<permission>)"

    # Message to kick a player now online
    already-online: "<#E0575B>Este jugador ya está conectado."

    # Message to show that the command cannot be executed via console
    player-command-usage: "<#E0575B>Este comando se deshabilitó a través de la consola."

    # Message shown when the plugin is reloaded.
    plugin-reload-message: "<#F2C14E>El plugin se recargó correctamente."

    # Message sent when a database operation has not been successfully performed
    database-error: "<#E0575B>Lo sentimos, no pudimos completar esta operación. Por favor, intenta de nuevo. [Error SQL]"

  other-messages:
    # Mensagem enviada para o uso do comando /logar
    message-login: "<#F2C14E>Usá el comando /login [contraseña]"

    # Mensagem enviada para o uso do comando /register
    message-register: "<#F2C14E>Usá el comando /register [contraseña] [contraseña]"

    # Mensagem enviada para o uso do comando /mudarsenha
    message-changepassword: "<#F2C14E>Usá el comando /changepassword [contraseña actual] [contraseña nueva]"

    # Message sent to use the /unregister command
    message-unregister: "<#F2C14E>Usá el comando /unregister [contraseña actual]"
