#          __             _
#  _ __   / /  ___   __ _(_)_ __
# | '_ \ / /  / _ \ / _` | | '_ \
# | | | / /__| (_) | (_| | | | | |
# |_| |_\____/\___/ \__, |_|_| |_|
#                   |___/

# Official Website: https://www.nickuc.com
# Discord: https://www.nickuc.com/discord

# WARNING: This is a translation made to nLogin. It will probably be compatible with all features of OpeNLogin.

# Hungarian translation made by simon21 <3

Messages:
  Title:
    # Message sent before login.
    before-login:
      title: "<gradient:#7F5AF0:#2CB67D><bold>Köszöntelek!</bold></gradient>"
      subtitle: "<#A0A0B0>Használat: /login [Jelszavad]"
      delays:
        start: 0
        duration: 9999
        end: 6
    # Message sent before registration.
    before-register:
      title: "<gradient:#7F5AF0:#2CB67D><bold>Köszöntelek!</bold></gradient>"
      subtitle: "<#A0A0B0>Használat: /register [Jelszavad] [Jelszavad]"
      delays:
        start: 0
        duration: 9999
        end: 6
    # Message sent after login.
    after-login:
      title: ""
      subtitle: "<#5EC26A>Sikeresen beléptél!"
      delays:
        start: 0
        duration: 60
        end: 6
    # Message sent after registration.
    after-register:
      title: ""
      subtitle: "<#5EC26A>Sikeresen beregisztráltál!"
      delays:
        start: 0
        duration: 60
        end: 6
    # Message sent when you miss a password.
    incorrect-password:
      title: ""
      subtitle: "<#E0575B>Hibás jelszó!"
      delays:
        start: 0
        duration: 60
        end: 6
    # Message sent when already logged in.
    already-login:
      title: ""
      subtitle: "<#E0575B>Te már be vagy lépve!"
      delays:
        start: 0
        duration: 60
        end: 6
    # Message sent when already registered.
    already-registered:
      title: ""
      subtitle: "<#E0575B>Te már be vagy regisztrálva!"
      delays:
        start: 0
        duration: 60
        end: 6
    # Message sent when passwords are not equal.
    passwords-dont-match:
      title: ""
      subtitle: "<#E0575B>Jelszavak nem azonosak!"
      delays:
        start: 0
        duration: 60
        end: 6
    # Message sent when session is continued.
    session-login:
      title: ""
      subtitle: "<#F2C14E>Bejelentkezésed folytatódik."
      delays:
        start: 0
        duration: 60
        end: 6
    # Message sent when you are an original player.
    premium-login:
      title: ""
      subtitle: "<#F2C14E>Fiókod eredetis, sikeresen beléptél!"
      delays:
        start: 0
        duration: 60
        end: 6
    # Message sent when a login session is continued.
    plugin-reload:
      title: ""
      subtitle: "<#5EC26A>A fájlok sikeresen újra lett töltve!"
      delays:
        start: 0
        duration: 60
        end: 6
    # Message sent from backup system.
    backup:
      title: ""
      subtitle: "<#5EC26A>Sikeresen visszaállitottál egy mentést."
      delays:
        start: 0
        duration: 90
        end: 6
    # Message sent from backup system.
    backup-error:
      title: ""
      subtitle: "<#E0575B>Nincs visszaállitási pont."
      delays:
        start: 0
        duration: 90
        end: 6
    # Message sent from security system.
    security-warning:
      title: ""
      subtitle: "<#E0575B>Biztonsági okokból figyelmeztetést küldtek chatre!"
      delays:
        start: 0
        duration: 60
        end: 6

  action-bar:
    # Message sent on the player's actionbar before login (singular).
    singular: "<#E0575B>Neked {0} másodperc van a {login/register}."

    # Message sent on the player's actionbar before login (plural).
    plural: "<#E0575B>Neked {0} másodperc van a {login/register}."

  delay-kick:
    # Message sent when a user takes a long time to register.
    register-kick: "<#E0575B>Nem sikerült beregisztrálni megadott időn belül!"

    # Message sent when a user takes a long time to log in.
    login-kick: "<#E0575B>Nem sikerült belépni megadott időn belül!"

  successful-operations:
    # Message when a user exchanges their password.
    password-changed: "<#5EC26A>Jelszavadat sikeresen megváltoztattuk!"

    # Message sent when a user successfully logs.
    successful-login: "<#5EC26A>Sikeresen beléptél!"

    # Message sent when a user logs in with an original account.
    successful-premium-login: "<#5EC26A>Automatikusan beléptettünk tégedet!"

    # Message sent when a user logs in using the same ip address.
    successful-session-login: "<#5EC26A>A bejelentkezésedet folytattuk."

    # Message sent when a user successfully registers.
    successful-register: "<#5EC26A>Sikeresen beregisztráltál."

    # Message sent when you force a player's login.
    forcelogin: "<#F2C14E>Beléptette: {0}"

    # Message sent when a player successfully unregister.
    unregister-kick: "<#E0575B>Sikeresen törölte a jelszavadat!"

    # Message sent when a configuration is finished
    config-finished: "<#5EC26A>Konfigfájlok sikeresen elkészültek!"

    # Message sent when a configuration is cancelled
    config-cancelled: "<#E0575B>Akció visszavonva!"

  kick-messages:
    # Message when a player tries to log on to the server with a small difference in the nickname.
    nick-already-registered: "<#E0575B>Ezt a nevet nem lehet megadni! <nickname>\n<#E0575B>Ezt a felhasználónévet már regisztráltuk <realname>\n\n<#E0575B>A belépéshez a becenevedet nagybetű / kisbetű nélkül kell használni!"

    # Message sent when a user misses many times.
    failed-many-times: "<#E0575B>Helytelenül adtad meg a jelszavadat!"

    # Message sent when password entered is incorrect.
    incorrect-password: "<#E0575B>Helytelen jelszó. Kérlek próbáld újra!"

    # Message sent when the security questions answer is incorrect.
    incorrect-answer: "<#E0575B>Helytelen válasz. Kérlek próbáld újra!"

    # Message sent when server is still starting.
    wait-server-start: "<#E0575B>A szerver nem indult el még teljesen.\n<#E0575B>Várj egy kicsit a csatlakozáshoz."

    # Message sent when an IP is blocked by suspected invasion.
    account-blocked: "<#E0575B>Címedet blokkolták a szerveren!\n<#E0575B>Fentmaradt várakozási idő: {0}"

    # Message sent when two-factor system temporary password is incorrect.
    incorrect-temporary-password: "<#E0575B>Rossz jelszó. Kérlek, próbáld meg újra."

    # Message to kick a user with an invalid nickname.
    invalid-nickname: "<#E0575B>Te neved hibás, ne tartalmazzon más szimbólumokat karaktereket!"

    # Message sent when the player's account has already been registered as unique.
    premium-account: "<#E0575B>Sajnáljuk, de egy prémium felhasználó már bejelentkezett erre a fiókra.\n<#E0575B>A szerveren való játékhoz más becenevet kell használnia.\n\nHa Ön a fiók tulajdonosa, próbálja meg újraindítani a Minecraft-ot."

  security-messages:
    # Message sent when a user was protected by the heuristic system.
    hacking-attack-warning:
      - ""
      - " <#E0575B><bold>BIZTONSÁGI ÉRTESíTÉS"
      - " <#E0575B>A biztonsági rendszer blokkolta az esetleges feltörési támadásokat a fiókjában."
      - " <#E0575B>Három sikertelen bejelentkezési kísérlet történt."
      - ""
      - " <#F2C14E><bold>TIP: <#F2C14E>Érdemes minden szerverre más jelszót használni!"
      - ""

    # Message sent when a user was protected more than once by the heuristic system.
    hacking-attack-warning2:
      - ""
      - " <#E0575B><bold>BIZTONSÁGI ÉRTESíTÉS"
      - " <#E0575B>A biztonsági rendszer le van tiltva {0} esetleges hackelési támadások a fiókjában."
      - " <#E0575B>Három sikertelen bejelentkezési kísérlet történt."
      - ""
      - " <#F2C14E><bold>TIP: <#F2C14E>Érdemes minden szerverre más jelszót használni!"
      - ""

    # Message sent when a user uses a weak password.
    weak-password:
      - ""
      - " <#E0575B>A regisztrált jelszó nem biztonságos."
      - " <#E0575B>Használjon betűket, számokat és szimbólumokat a biztonság javítása érdekében."
      - " <#E0575B>Példa jelszóra: {0}"
      - ""

    # Message sent when a player has not yet registered the security questions.
    security-question-warn-message:
      - ""
      - " <#E0575B><bold>BIZTONSÁGI KÉRDÉSEK"
      - " <#A0A0B0>Hajtsa végre a [white]/sq add <#A0A0B0>parancsot a regisztrációhoz."
      - " <#E0575B>biztonsági kérdéseket és ezzel"
      - " <#A0A0B0>csökkentse a feltörés esélyét."
      - ""

    # Message sent when a security question is being added.
    security-question-add:
      - ""
      - " <#F2C14E>{0}"
      - ""
      - " <#A0A0B0>Segítségért [white]'cancel' <#A0A0B0>hogy törölje a műveletet."
      - " [obfuscated]attintson erre az üzenetre egy újabb kérdést kapjon előállításához."
      - ""

    # Message sent when a security question should be reviewed.
    security-question-check:
      - ""
      - " <#5EC26A>A megerősítés előtt ellenőrizze az információkat:"
      - ""
      - " <#A0A0B0>{0}: [white]'{1}'"
      - ""
      - " <#5EC26A>Ha biztos benne, írja be [white]'confirm'<#5EC26A>."
      - " <#F2C14E>Ha valamit rosszul írt be, írja be [white]'repeat'<#F2C14E>."
      - " <#E0575B>Ha meg akarja szakítani ezt a műveletet, írja be [white]'cancel'<#E0575B>."
      - ""

    # Message sent when security questions are requested.
    security-question-request:
      - ""
      - " <#5EC26A>Sajnáljuk, de személyazonosság-megerősítés szükséges."
      - " <#5EC26A>Válaszoljon az alábbi kérdésre a csevegésben:"
      - ""
      - " <#56CCF2>{0}"
      - ""

    # Message sent when security questions are requested a second time.
    security-question-request2:
      - "<#5EC26A>Következő kérdés..."
      - ""
      - " <#56CCF2>{0}"
      - ""

  error-messages:
    # Message sent when you are already logged in.
    already-login: "<#E0575B>Te már be vagy lépve."

    # Message sent when a user is already logged in.
    already-login2: "<#E0575B>Ez a felhasználó már be van jelentkezve."

    # Message sent when a nickname has already been registered.
    already-registered: "<#E0575B>Ezt a nevet már regisztrálták."

    # Message sent when a nickname has not yet been registered.
    not-registered: "<#E0575B>Ezt a nevet még nem regisztrálták."

    # Message sent when the entered password is not equal to the second.
    passwords-dont-match: "<#E0575B>A jelszavak nem azonosak."

    # Message sent when a player does not confirm your password.
    need-password-confirmation: "<#E0575B>Meg kell erősítenie jelszavát."

    # Message sent when IP limits per player pass the limit.
    address-limiter-warning: "<#E0575B>Elérted a felhasználódnak az ip limitjét!"

    # Message sent when a player tries to change password by entering the same password as the current.
    password-same-as-old: "<#E0575B>A megadott jelszó megegyezik a jelenlegi jelszóval."

    # Message sent when the password entered is too large.
    password-too-large: "<#E0575B>A megadott jelszó túl nagy."

    # Message sent when the password entered is too small.
    password-too-small: "<#E0575B>A megadott jelszó túl kicsi."

    # Message sent when a user attempts to disable nLogin using PlugMan/System.
    plugman-block: "<#E0575B>Itt nem érheti meg a bejelentkezési bővítményt."

    # Message when a player does not possess the required permission.
    insufficient-permissions: "<#E0575B>Nincs jogod ehez! <#A0A0B0>(<permission>)"

    # Message to show the use of a command.
    command-usage: "<#E0575B>Használnia kell {0}."

    # Message to kick a player now online.
    already-online: "<#E0575B>Ez a játékos már fent van."

    # Message to display that a player is not online.
    offline-error: "<#E0575B>Ez a játékos offline."

    # Message to show that the command cannot be executed via console.
    player-command-usage: "<#E0575B>Ezt a parancsot a konzolon keresztül letiltották."

    # Message to show that a command can only be executed by the console.
    console-command-usage: "<#E0575B>Ez a parancs csak a konzolon keresztül használható."

    # Message shown when the plugin is reloaded.
    plugin-reload-message: "<#F2C14E>Fájlok újratöltve."

    # Message shown when the function of a command is disabled.
    command-function-disabled: "<#E0575B>A {0} parancs funkciója le van tiltva."

    # Message sent when a database operation has not been successfully performed.
    database-error: "<#E0575B>Sajnos nem tudtuk befejezni ezt a műveletet. Kérlek próbáld újra. [SQL FAIL]"

  twofactor:
    # Message sent when a user does not have a temporary password.
    no-temporary-password: "<#E0575B>Ideiglenes jelszó még nem lett létrehozva."

    # Message sent when a user does not have a linked account.
    no-twofactor-registered: "<#E0575B>Nincs {0} -fiókod."

    # Message sent when a user has already linked an account.
    twofactor-already-registered: "<#E0575B>Már regisztrálta a következőt: {0}."

    # Message sent when a user removes their account from two factors.
    twofactor-unregistered: "§eA(z) {0} szolgáltatást sikeresen leválasztottuk"

    # Message sent when a user confirms their two-factor account.
    confirmed-account: "<#5EC26A>{0} -fiókját sikeresen regisztráltuk"

    # Message sent when a confirmation message is sent.
    confirmation-message-sent: "<#A0A0B0>Megerősítő kódot küldtünk Önnek {0} (§f{1}§7)."

    switch:
      # Message sent when a user activates the two-factor.
      enabled: "<#5EC26A>A kétfaktoros funkció aktiválódott."

      # Message sent when a user disables the two-factor.
      disabled: "<#E0575B>A kétfaktoros funkció kikapcsolva."

    recover:
      # Message sent when a user does not provide the same two-factor account registered.
      twofactor-not-equal: "<#E0575B>A megadott {0} nem ugyanaz, mint a regisztrált."

      # Message sent when a user requests a recovery request in a short period of time.
      message-sent: "<#5EC26A>Helyreállítási üzenetet küldtünk a társított fiókjába."

      # Message sent when a user recovers his account and his password is set automatically.
      automatic-change: "<#5EC26A>Jelszavát automatikusan megváltoztatta [white]erre '{0}'."

    discord:
      # Message sent when a user links his Discord account.
      account-linked: "<#5EC26A>A Discord konfigurációja sikeresen frissítve. \N <#5EC26A>Csatlakoztak a[white] {0} <#5EC26A>account fiókhoz."

  other-messages:
    # Hover message: /login.
    hover-message-login: "<#A0A0B0>Kattintson ide a parancs végrehajtásához és a gyors bejelentkezéshez."

    # Hover message: /register.
    hover-message-register: "<#A0A0B0>Kattintson ide a parancs végrehajtásához és a gyors regisztrációhoz."

    # Command usage: /login
    message-login: "<#F2C14E>Használd ezt a parancsot <#A0A0B0>/login [jelszó]<#F2C14E>."

    # Command usage: /register
    message-register: "<#F2C14E>Használd ezt a parancsot <#A0A0B0>/register [jelszó] [jelszó]<#F2C14E>."

    # Command usage: /changepassword
    message-changepassword: "<#F2C14E>Használd ezt a parancsot <#A0A0B0>/changepassword [régi jelszó] [új jelszó]<#F2C14E>."

    # Command usage: /checkprofile
    message-verify: "<#F2C14E>Használd ezt a parancsot <#A0A0B0>/checkprofile [player]<#F2C14E>."

    # Command usage: /unregister
    message-unregister: "<#F2C14E>Használd ezt a parancsot <#A0A0B0>/unregister [aktuális jelszó]<#F2C14E>."
