#    ___                __  __
#   /___\_ __   ___  /\ \ \/ /  ___   __ _(_)_ __
#  //  // '_ \ / _ \/  \/ / /  / _ \ / _` | | '_ \
# / \_//| |_) |  __/ /\  / /__| (_) | (_| | | | | |
# \___/ | .__/ \___\_\ \/\____/\___/ \__, |_|_| |_|
#       |_|                          |___/

# Site oficial: https://www.nickuc.com
# Discord: https://www.nickuc.com/discord

Messages:
  Title:
    # Mensagem enviada antes de logar
    before-login:
      title: "<gradient:#7F5AF0:#2CB67D><bold>¡Bienvenido!</bold></gradient>"
      subtitle: "<#A0A0B0>Usa: /login [contraseña]."
      delays:
        start: 0
        duration: 9999
        end: 6
    # Mensagem enviada antes de registrar
    before-register:
      title: "<gradient:#7F5AF0:#2CB67D><bold>¡Bienvenido!</bold></gradient>"
      subtitle: "<#A0A0B0>Usa: /register [contraseña] [contraseña]."
      delays:
        start: 0
        duration: 9999
        end: 6
    # Mensagem enviada após logar
    after-login:
      title: ""
      subtitle: "<#5EC26A>¡Has inicio sesión con éxito!"
      delays:
        start: 0
        duration: 30
        end: 6
    # Mensagem enviada após registrar
    after-register:
      title: ""
      subtitle: "<#5EC26A>¡Te has registrado con éxito!"
      delays:
        start: 0
        duration: 30
        end: 6

  delay-kick:
    # Mensagem enviada quando um usuário demora muito para se registrar
    register-kick: "<#E0575B>Has tardado mucho en registrarte."

    # Mensagem enviada quando um usuário demora muito para se logar
    login-kick: "<#E0575B>Has tardado mucho en iniciar sesión."

  successful-operations:
    # Mensagem quando um usuário troca a sua senha
    password-changed: "<#5EC26A>Su contraseña ha cambiado con éxito."

    # Mensagem enviada quando um usuário loga com sucesso
    successful-login: "<#5EC26A>Has iniciado sesión con éxito."

    # Mensagem enviada quando um usuário se registra com sucesso
    successful-register: "<#5EC26A>Te has registrado con éxito."

    # Mensagem enviada quando um jogador se desregistra com sucesso
    unregister-kick: "<#E0575B>Registro cancelado con éxito."

  kick-messages:
    # Mensagem quando um jogador tenta se logar no servidor com uma pequena diferença no nick
    nick-already-registered: "<#E0575B>No podés entrar con el nick <nickname>\n<#E0575B>Este nick ya ha sido registrado como <realname>\n\n<#E0575B>Para entrar, debes ingresar tu nick sin letras mayúsculas/minúsculas"

    # Mensagem enviada quando um usuário erra muitas vezes
    failed-many-times: "<#E0575B>La contraseña ingresada es incorrecta."

    # Mensagem enviada quando a senha inserida é incorreta
    incorrect-password: "<#E0575B>¡Contraseña incorrecta! Vuelve a intentarlo."

  error-messages:
    # Mensaje enviado cuando ya está conectado.
    already-login: "<#E0575B>Ya has iniciado sesión."

    # Mensaje enviado cuando ya se ha registrado un apodo.
    already-registered: "<#E0575B>Este usuario ya ha sido registrado."

    # Mensaje enviado cuando aún no se ha registrado un apodo.
    not-registered: "<#E0575B>Este usuario aún no se ha registrado."

    # Mensagem enviada quando a senha inserida não é igual a segunda
    passwords-dont-match: "<#E0575B>Las contraseñas no coinciden."

    # Mensagem enviada quando um jogador tenta mudar senha inserindo a mesma senha que a atual
    password-same-as-old: "<#E0575B>La contraseña introducida es la misma que la actual."

    # Mensagem enviada quando a senha inserida é muito grande
    password-too-large: "<#E0575B>La contraseña introducida es muy larga."

    # Mensagem enviada quando a senha inserida é muito pequena
    password-too-small: "<#E0575B>La contraseña introducida es muy corta."

    # Mensagem quando um jogador não possuí a permissão necessária
    insufficient-permissions: "<#E0575B>No tienes permiso para ejecutar este comando. <#A0A0B0>(<permission>)"

    # Mensagem para kickar um jogador já online
    already-online: "<#E0575B>Este usuario ya está en línea."

    # Mensagem para mostrar que o comando não pode ser executado via console
    player-command-usage: "<#E0575B>Este comando se ha inhabilitado a través de la consola."

    # Mensagem mostrada quando o plugin é recarregado
    plugin-reload-message: "<#F2C14E>El plugin se ha recargado con éxito."

    # Mensaje enviado cuando una operación de base de datos no se ha realizado correctamente
    database-error: "<#E0575B>Lo sentimos, no pudimos completar esta operación. Inténtalo de nuevo. [SQL FAIL]"

  other-messages:
    # Mensagem enviada para o uso do comando /logar
    message-login: "<#F2C14E>Utilice el comando <#A0A0B0>/login [contraseña]<#F2C14E>."

    # Mensagem enviada para o uso do comando /register
    message-register: "<#F2C14E>Utilice el comando <#A0A0B0>/register [contraseña] [contraseña]<#F2C14E>."

    # Mensagem enviada para o uso do comando /mudarsenha
    message-changepassword: "<#F2C14E>Utilice el comando <#A0A0B0>/changepassword [contraseña actual] [nueva contraseña]<#F2C14E>."

    # Mensaje enviado para usar el comando /unregister
    message-unregister: "<#F2C14E>Utilice el comando <#A0A0B0>/unregister [contraseña actual]<#F2C14E>."
